FROM rockylinux:9
RUN dnf -y upgrade
RUN dnf -y --enablerepo=devel install make automake autoconf libtool mariadb-devel epel-release libsodium-devel
WORKDIR /code
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]